/**
 * backend/db/init.js
 *
 * Database Initializer – SkillSphere
 * ====================================
 * Runs once at server startup.  Creates all application tables and indexes
 * if they do not already exist.
 *
 * Rules:
 *   - NEVER import better-sqlite3 here. Use only backend/config/db.js.
 *   - All primary keys are UUID TEXT (generated by the uuid package in JS).
 *   - All tables use IF NOT EXISTS to be safe across restarts.
 *   - Foreign keys are already enabled by db.js (PRAGMA foreign_keys = ON).
 */

"use strict";

const db = require("../config/db");

// ─────────────────────────────────────────────────────────────────
//  TABLE DEFINITIONS
// ─────────────────────────────────────────────────────────────────

const CREATE_USERS = `
  CREATE TABLE IF NOT EXISTS users (
    id          TEXT    PRIMARY KEY,                         -- UUID v4
    name        TEXT    NOT NULL,
    email       TEXT    NOT NULL UNIQUE,
    password    TEXT    NOT NULL,                            -- bcrypt hash
    role        TEXT    NOT NULL DEFAULT 'student'
                        CHECK (role IN ('student', 'instructor')),
    avatar_url  TEXT,
    bio         TEXT,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
  )
`;

const CREATE_WORKSHOPS = `
  CREATE TABLE IF NOT EXISTS workshops (
    id           TEXT    PRIMARY KEY,                        -- UUID v4
    instructor_id TEXT   NOT NULL
                         REFERENCES users(id) ON DELETE CASCADE,
    title        TEXT    NOT NULL,
    description  TEXT,
    category     TEXT    NOT NULL,
    skill_level  TEXT    NOT NULL DEFAULT 'beginner'
                         CHECK (skill_level IN ('beginner', 'intermediate', 'advanced')),
    price        REAL    NOT NULL DEFAULT 0
                         CHECK (price >= 0),
    max_seats    INTEGER NOT NULL DEFAULT 20
                         CHECK (max_seats > 0),
    location     TEXT,
    is_online    INTEGER NOT NULL DEFAULT 1                  -- 0 = false, 1 = true
                         CHECK (is_online IN (0, 1)),
    status       TEXT    NOT NULL DEFAULT 'draft'
                         CHECK (status IN ('draft', 'published', 'cancelled', 'completed')),
    scheduled_at TEXT,
    meet_link    TEXT,
    cover_url    TEXT,
    created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
  )
`;

const CREATE_BOOKINGS = `
  CREATE TABLE IF NOT EXISTS bookings (
    id           TEXT    PRIMARY KEY,                        -- UUID v4
    workshop_id  TEXT    NOT NULL
                         REFERENCES workshops(id) ON DELETE CASCADE,
    student_id   TEXT    NOT NULL
                         REFERENCES users(id) ON DELETE CASCADE,
    status       TEXT    NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'confirmed', 'cancelled', 'attended')),
    paid_amount  REAL    NOT NULL DEFAULT 0
                         CHECK (paid_amount >= 0),
    booked_at    TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    -- A student can only book a given workshop once
    UNIQUE (workshop_id, student_id)
  )
`;

const CREATE_REVIEWS = `
  CREATE TABLE IF NOT EXISTS reviews (
    id           TEXT    PRIMARY KEY,                        -- UUID v4
    workshop_id  TEXT    NOT NULL
                         REFERENCES workshops(id) ON DELETE CASCADE,
    reviewer_id  TEXT    NOT NULL
                         REFERENCES users(id) ON DELETE CASCADE,
    rating       INTEGER NOT NULL
                         CHECK (rating BETWEEN 1 AND 5),
    comment      TEXT,
    created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    -- One review per student per workshop
    UNIQUE (workshop_id, reviewer_id)
  )
`;

// ─────────────────────────────────────────────────────────────────
//  INDEX DEFINITIONS
//  Improves query performance for the most common access patterns.
// ─────────────────────────────────────────────────────────────────

const INDEXES = [
  // users
  "CREATE INDEX IF NOT EXISTS idx_users_email    ON users(email)",
  "CREATE INDEX IF NOT EXISTS idx_users_role     ON users(role)",

  // workshops
  "CREATE INDEX IF NOT EXISTS idx_workshops_instructor ON workshops(instructor_id)",
  "CREATE INDEX IF NOT EXISTS idx_workshops_status     ON workshops(status)",
  "CREATE INDEX IF NOT EXISTS idx_workshops_category   ON workshops(category)",

  // bookings
  "CREATE INDEX IF NOT EXISTS idx_bookings_workshop ON bookings(workshop_id)",
  "CREATE INDEX IF NOT EXISTS idx_bookings_student  ON bookings(student_id)",
  "CREATE INDEX IF NOT EXISTS idx_bookings_status   ON bookings(status)",

  // reviews
  "CREATE INDEX IF NOT EXISTS idx_reviews_workshop  ON reviews(workshop_id)",
  "CREATE INDEX IF NOT EXISTS idx_reviews_reviewer  ON reviews(reviewer_id)",
];

// ─────────────────────────────────────────────────────────────────
//  INITIALIZER
// ─────────────────────────────────────────────────────────────────

/**
 * Create all tables and indexes inside a single transaction.
 * Safe to call on every server start – uses IF NOT EXISTS throughout.
 */
function initDatabase() {
  console.log("[DB Init] Running database initialization…");

  db.transaction(() => {
    // Tables
    db.run(CREATE_USERS);
    db.run(CREATE_WORKSHOPS);
    db.run(CREATE_BOOKINGS);
    db.run(CREATE_REVIEWS);

    // Indexes
    for (const indexSql of INDEXES) {
      db.run(indexSql);
    }
  });

  console.log("[DB Init] ✓ Tables: users, workshops, bookings, reviews");
  console.log(`[DB Init] ✓ ${INDEXES.length} indexes created / verified`);
}

module.exports = { initDatabase };
